source "https://rubygems.org"
gem "just-the-docs", ">= 0.3.3"
group :jekyll_plugins do
  gem "github-pages"                 , ">= 209" # GitHub Pages
  gem "jekyll-optional-front-matter" , ">= 0.3.2" # GitHub Pages
  gem "jekyll-default-layout"        , ">= 0.1.4" # GitHub Pages
  gem "jekyll-titles-from-headings"  , ">= 0.5.3" # GitHub Pages
  gem "jekyll-readme-index"          , ">= 0.3.0" # GitHub Pages
  gem "jekyll-relative-links"        , ">= 0.6.1" # GitHub Pages
  gem 'jekyll-include-cache'         , '>= 0.2.1' # GitHub Pages
end
